apiVersion: apps/v1
kind: Deployment
metadata:
  name: contact-insert-consumer-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contact-insert-consumer-api
  template:
    metadata:
      labels:
        app: contact-insert-consumer-api
    spec:
      containers:
      - name: contact-insert-consumer-api
        image: maxcedro/contactsinsertconsumer-new:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 6060
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:6060"
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: contact-insert-consumer-api-secrets
              key: DefaultConnection
        - name: SecretJWT
          valueFrom:
            secretKeyRef:
              name: contact-insert-consumer-api-secrets
              key: SecretJWT
        - name: MassTransit__User
          valueFrom:
            secretKeyRef:
              name: contact-insert-consumer-api-secrets
              key: User
        - name: MassTransit__Password
          valueFrom:
            secretKeyRef:
              name: contact-insert-consumer-api-secrets
              key: Password
        - name: MassTransit__QueueName
          valueFrom:
            configMapKeyRef:
              name: contact-insert-consumer-api-configmap
              key: QueueName
        - name: MassTransit__Server
          valueFrom:
            configMapKeyRef:
              name: contact-insert-consumer-api-configmap
              key: Server
        - name: Integrations__ContactConsult__BasePath
          valueFrom:
            configMapKeyRef:
              name: contact-insert-producer-api-configmap
              key: BasePath
