apiVersion: v1
kind: Service
metadata:
  name: contact-insert-consumer-api-nodeport
spec:
  selector:
    app: contact-insert-consumer-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 6060
      nodePort: 30084
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: contact-insert-consumer-api-loadbalancer
spec:
  selector:
    app: contact-insert-consumer-api
  ports:
    - protocol: TCP
      port: 5010
      targetPort: 6060
  type: LoadBalancer
